apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  labels:
    app: monitoring-stack
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/k8s-file-upload-lab  # Update with your repo URL
    targetRevision: main
    path: charts/monitoring-stack
    helm:
      valueFiles:
      - values-aws.yaml
      parameters:
      - name: namespace.create
        value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10

